Fixes missing post titles in the P2P metabox
moderntribe/tribe-libs pull request #111
Opened 2022-03-21 15:44 UTC by clontztopher

- Based on [external PR](https://github.com/moderntribe/harvard-school-public-health/pull/23)

2022-03-22 05:36 UTC, defunctl requested changes
Just some minor formatting but this looks good. Thanks!

2022-03-22 05:36 UTC, defunctl commented on src/P2P/Titles_Filter.php
> +		if ( empty($title) && $object instanceof \WP_Post ) {
```suggestion
		if ( empty( $title ) && $object instanceof \WP_Post ) {
```

2022-03-22 05:36 UTC, defunctl commented on src/P2P/Titles_Filter.php
> +		if ( empty($title) && $object instanceof \WP_Post ) {
```suggestion
		if ( empty( $title ) && $object instanceof \WP_Post ) {
```

2022-03-23 14:27 UTC, dpellenwood approved these changes
Once you've made the formatting changes suggested, you should be good to merge. Thanks Chris!

2022-03-23 14:43 UTC, defunctl commented
I'll do a release along with my queues branch once this is in there.

2022-03-23 14:48 UTC, merged