Feature/routing
moderntribe/tribe-libs pull request #70
Opened 2020-10-02 12:57 UTC by mmcachran

Adds routing to Tribe Libs.

2020-10-19 22:03 UTC, defunctl commented
Hey @mmcachran,

Looks like all tests are failing due to invalid JSON in the composer.lock, can you please get the test passing?

Thanks!

2021-04-02 18:15 UTC, nickpelton reviewed
Going to try and give this a test in this next week.

2021-04-02 22:36 UTC, defunctl requested changes
Some things to chat about here, but looks like a great place to start.

In general, please add `@action` and `@filter` comments to your methods if they are hooked into WordPress. Makes it easier for other developers to see that, e.g. `@action init` or `@filter the_content` etc....

Would very much like to see some tests for this, just reach out if need some direction.

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_REST_Route.php
> +<?php // phpcs:disable WordPress.Files.FileName.NotHyphenatedLowercase
I think we should actually name this `Abstract_Rest_Route` and make this work on case sensitive file systems: https://github.com/moderntribe/square-one/pull/678/files#r606454579

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_REST_Route.php
> +		return 'wp/v2';
How often would this change across an entire project do you think?

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +<?php // phpcs:disable WordPress.Files.FileName.NotHyphenatedLowercase
Don't think this is needed in this class

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +	abstract public function register() : void;
As mentioned in the other PR, we should not register any hooks in our instances, so probably won't need this.

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +	public function get_name() : string {
Same deal here for `:` spacing, please.

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +			'GET',
Should use the `WP_REST_Server` constants here as well

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +	public function activate( $wp ) : void {
Let's chat about moving this into a subscriber instead.

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +			$protocol         = filter_input( INPUT_SERVER, 'SERVER_PROTOCOL', FILTER_SANITIZE_SPECIAL_CHARS );
Doesn't this not work on all PHP configurations, e.g. those using fastcgi?

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +		header( 'HTTP/1.1 403 Forbidden' );
We don't actually know which HTTP version a server could be using.

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Abstract_Route.php
> +		wp_die( 'Not Authorized' );
```suggestion
		wp_die( 'Not Authorized', 403 );
```
Wouldn't this work properly instead?

2021-04-02 22:36 UTC, defunctl commented on src/Routes/Router.php
> +class Router extends Abstract_Subscriber {
Ah, I see now that you're extending the Container's subscriber for this. I'm not sure this is a very good idea, in the sense that responsibility for a subscriber should be to register instances to WordPress hooks. This should really be its own stand alone/testable class that is instead registered for the proper hooks in the Router_Subscriber.

2021-04-22 12:51 UTC, merged

2021-04-29 22:51 UTC, defunctl commented
@mmcachran this failed PHPCS and shouldn't have been merged (sorry we didn't have this set up to prevent that): https://github.com/moderntribe/tribe-libs/runs/2401691633

2021-04-29 23:05 UTC, defunctl commented
@mmcachran and @nickpelton  A few other issues here:

1. https://github.com/moderntribe/square1-routes/ should be created via: https://github.com/moderntribe/tribe-libs#adding-packages
1. Then it should be added to https://github.com/moderntribe/tribe-libs/blob/master/monorepo-builder.php#L38
1. It should then get registered to packagist.
1. I realize the automated workflow bumped the version, but given this is new functionality following [semver](https://semver.org/) it should have been bumped to `3.5.0`. Ideally, rolling back the releases and releasing this with the proper version, and they have to be manually removed from packagist.