Update block templates to match coding standards
moderntribe/tribe-libs pull request #98
Opened 2021-12-14 16:13 UTC by tarecord

After generating some blocks recently, I noticed that the templates do not match our current coding standards.

2021-12-14 16:14 UTC, nickpelton approved these changes
Heck Yeah! 🚀 

Note, we'll need to do a release to ship this. I'll plan on doing it in the new year.

2021-12-14 16:19 UTC, ChrisMKindred approved these changes
🌮

2021-12-14 16:35 UTC, defunctl commented
@tarecord Thanks so much for doing this!

I started a v2 conversion a long time ago but never got to finish it. 

There's a few more you could include for this release if you have time:

1. https://github.com/moderntribe/tribe-libs/commit/9fabe2c566c1a506116e9e89c72322c37ade8b5b#diff-c4b17a47324748d068e45da15eb798ea25fcc161d1ffe2835aa6629e76a77dd3
2. https://github.com/moderntribe/tribe-libs/commit/eca41c95b84c0e6c38a3127dc24b836374d12a4b#diff-c4b17a47324748d068e45da15eb798ea25fcc161d1ffe2835aa6629e76a77dd3
3. https://github.com/moderntribe/tribe-libs/commit/a83f9013c07828880b46866f15175c568f705e7e#diff-c4b17a47324748d068e45da15eb798ea25fcc161d1ffe2835aa6629e76a77dd3
4. https://github.com/moderntribe/tribe-libs/commit/c34854b6fbf54658859a50c8c808856652ee5bf9#diff-c4b17a47324748d068e45da15eb798ea25fcc161d1ffe2835aa6629e76a77dd3
5. https://github.com/moderntribe/tribe-libs/commit/b29b16a91346187e6008555c5f8908456b4fd5d8#diff-c4b17a47324748d068e45da15eb798ea25fcc161d1ffe2835aa6629e76a77dd3

2021-12-14 16:39 UTC, defunctl commented
@tarecord oh, add an item to the `Unreleased` changelog section as well, that gets updated to the latest release once the monorepo push goes out.

2021-12-14 16:41 UTC, defunctl requested changes
Add a changelog item and if you have time, there are a few other items that will also fail linting on the JS side of things

2021-12-28 21:11 UTC, defunctl approved these changes
Tested on a project with v2.0 coding standards and it works perfectly :rocket:

2022-01-31 15:56 UTC, dpellenwood approved these changes
This is wonderful. Just one minor tweak, then good to merge. Thanks so much @tarecord !

2022-01-31 15:56 UTC, dpellenwood commented on src/Generators/templates/component/source.js
> +// import * as tools from 'utils/tools';
Feel free to just delete this line. It's unnecessary in the boilerplate.

2022-02-10 20:14 UTC, merged